# Generated by Django 3.2.7 on 2021-09-20 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210920_0245'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='bird',
            index_together={('slug',)},
        ),
    ]
