# Generated by Django 3.2.7 on 2021-09-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_bird_index_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='sound',
            field=models.FileField(blank=True, upload_to='birds/%Y/%m/%d'),
        ),
    ]
